"""
Technical Analyst node — rule-based, no LLM call.

This is the node from the cost-control decision: RSI/SMA are numbers,
not judgment calls, so a small set of explainable if/elif rules is more
honest here than paying for an LLM to reason about arithmetic it isn't
actually needed for. The `reasoning` string is still human-readable
because agent_opinions.reasoning should always be, but it's built from
an f-string, not generated by a model.
"""

from __future__ import annotations

from typing import Awaitable, Callable

from app.agent.data_sources import PriceDataSource
from app.agent.indicators import rsi, sma
from app.agent.state import AgentOpinion, GraphState


def make_technical_analyst_node(
    price_source: PriceDataSource,
) -> Callable[[GraphState], Awaitable[dict]]:
    async def node(state: GraphState) -> dict:
        symbol = state["symbol"]
        as_of = state["as_of"]

        # 40 calendar days of daily bars comfortably covers the 21
        # trading-day minimum RSI-14 needs (14 changes + 1 seed close),
        # accounting for weekends/holidays.
        bars = await price_source.get_recent_bars(symbol, as_of, lookback_days=40)
        closes = [bar.close for bar in bars]

        rsi_14 = rsi(closes, period=14)
        sma_20 = sma(closes, period=20)

        if rsi_14 is None or sma_20 is None:
            opinion = AgentOpinion(
                agent_name="technical_analyst",
                opinion="HOLD",
                confidence=None,
                reasoning=(
                    f"Only {len(closes)} price bars available — not enough "
                    "history to compute RSI-14/SMA-20 reliably."
                ),
                raw_output={"n_bars": len(closes)},
            )
            return {"technical_opinion": opinion}

        current_price = closes[-1]

        if rsi_14 < 30 and current_price > sma_20:
            call, confidence = "BUY", 0.65
            reasoning = (
                f"RSI-14 at {rsi_14:.1f} is oversold while price "
                f"({current_price}) holds above SMA-20 ({sma_20:.2f}) — "
                "reads as a reversal setup, not a falling knife."
            )
        elif rsi_14 > 70:
            call, confidence = "SELL", 0.60
            reasoning = f"RSI-14 at {rsi_14:.1f} is overbought."
        elif current_price > sma_20:
            call, confidence = "BUY", 0.55
            reasoning = (
                f"Price ({current_price}) above SMA-20 ({sma_20:.2f}), "
                f"RSI-14 neutral at {rsi_14:.1f} — mild uptrend, no extremes."
            )
        else:
            call, confidence = "HOLD", 0.50
            reasoning = (
                f"No clear signal — RSI-14 {rsi_14:.1f}, price at or below "
                f"SMA-20 ({sma_20:.2f})."
            )

        opinion = AgentOpinion(
            agent_name="technical_analyst",
            opinion=call,
            confidence=confidence,
            reasoning=reasoning,
            raw_output={
                "rsi_14": float(rsi_14),
                "sma_20": float(sma_20),
                "current_price": float(current_price),
                "n_bars": len(closes),
            },
        )
        return {"technical_opinion": opinion}

    return node
